<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Atlas\Enums;

/**
 * GENERATED by tools/generate-enums.php — do not edit by hand.
 *
 * Every ISO 639-3 code spoken in a country in the catalogue.
 *
 * Case names are upper-cased because a PHP case name is case-sensitive and `swa` beside
 * `SWA` would read as two languages; the backing value keeps the canonical lower-case form.
 *
 * 156 cases, generated from resources/data/countries.php. Regenerate with
 * `php tools/generate-enums.php`; `--check` gates it in CI.
 */
enum Language: string
{
    case AFR = 'afr';
    case AMH = 'amh';
    case ARA = 'ara';
    case ARC = 'arc';
    case AYM = 'aym';
    case AZE = 'aze';
    case BAR = 'bar';
    case BEL = 'bel';
    case BEN = 'ben';
    case BER = 'ber';
    case BIS = 'bis';
    case BJZ = 'bjz';
    case BOS = 'bos';
    case BUL = 'bul';
    case BWG = 'bwg';
    case CAL = 'cal';
    case CAT = 'cat';
    case CES = 'ces';
    case CHA = 'cha';
    case CKB = 'ckb';
    case CMN = 'cmn';
    case CRS = 'crs';
    case DAN = 'dan';
    case DEU = 'deu';
    case DIV = 'div';
    case DZO = 'dzo';
    case ELL = 'ell';
    case ENG = 'eng';
    case EST = 'est';
    case EUS = 'eus';
    case FAO = 'fao';
    case FAS = 'fas';
    case FIJ = 'fij';
    case FIL = 'fil';
    case FIN = 'fin';
    case FRA = 'fra';
    case GIL = 'gil';
    case GLE = 'gle';
    case GLG = 'glg';
    case GLV = 'glv';
    case GRN = 'grn';
    case GSW = 'gsw';
    case HAT = 'hat';
    case HEB = 'heb';
    case HER = 'her';
    case HGM = 'hgm';
    case HIF = 'hif';
    case HIN = 'hin';
    case HMO = 'hmo';
    case HRV = 'hrv';
    case HUN = 'hun';
    case HYE = 'hye';
    case IND = 'ind';
    case ISL = 'isl';
    case ITA = 'ita';
    case JAM = 'jam';
    case JPN = 'jpn';
    case KAL = 'kal';
    case KAT = 'kat';
    case KAZ = 'kaz';
    case KCK = 'kck';
    case KHI = 'khi';
    case KHM = 'khm';
    case KIN = 'kin';
    case KIR = 'kir';
    case KON = 'kon';
    case KOR = 'kor';
    case KWN = 'kwn';
    case LAO = 'lao';
    case LAT = 'lat';
    case LAV = 'lav';
    case LIN = 'lin';
    case LIT = 'lit';
    case LOZ = 'loz';
    case LTZ = 'ltz';
    case LUA = 'lua';
    case MAH = 'mah';
    case MEY = 'mey';
    case MFE = 'mfe';
    case MKD = 'mkd';
    case MLG = 'mlg';
    case MLT = 'mlt';
    case MON = 'mon';
    case MRI = 'mri';
    case MSA = 'msa';
    case MYA = 'mya';
    case NAU = 'nau';
    case NBL = 'nbl';
    case NDC = 'ndc';
    case NDE = 'nde';
    case NDO = 'ndo';
    case NEP = 'nep';
    case NFR = 'nfr';
    case NIU = 'niu';
    case NLD = 'nld';
    case NNO = 'nno';
    case NOB = 'nob';
    case NOR = 'nor';
    case NRF = 'nrf';
    case NSO = 'nso';
    case NYA = 'nya';
    case NZS = 'nzs';
    case OCI = 'oci';
    case PAP = 'pap';
    case PAU = 'pau';
    case PIH = 'pih';
    case POL = 'pol';
    case POR = 'por';
    case PRS = 'prs';
    case PUS = 'pus';
    case QUE = 'que';
    case RAR = 'rar';
    case ROH = 'roh';
    case RON = 'ron';
    case RUN = 'run';
    case RUS = 'rus';
    case SAG = 'sag';
    case SIN = 'sin';
    case SLK = 'slk';
    case SLV = 'slv';
    case SMI = 'smi';
    case SMO = 'smo';
    case SNA = 'sna';
    case SOM = 'som';
    case SOT = 'sot';
    case SPA = 'spa';
    case SQI = 'sqi';
    case SRD = 'srd';
    case SRP = 'srp';
    case SSW = 'ssw';
    case SWA = 'swa';
    case SWE = 'swe';
    case TAM = 'tam';
    case TET = 'tet';
    case TGK = 'tgk';
    case THA = 'tha';
    case TIR = 'tir';
    case TKL = 'tkl';
    case TOI = 'toi';
    case TON = 'ton';
    case TPI = 'tpi';
    case TSN = 'tsn';
    case TSO = 'tso';
    case TUK = 'tuk';
    case TUR = 'tur';
    case TVL = 'tvl';
    case UKR = 'ukr';
    case URD = 'urd';
    case UZB = 'uzb';
    case VEN = 'ven';
    case VIE = 'vie';
    case XHO = 'xho';
    case ZDJ = 'zdj';
    case ZHO = 'zho';
    case ZIB = 'zib';
    case ZUL = 'zul';
}
