<?php

declare(strict_types=1);

/**
 * Generates the typed enums that mirror the shipped dataset.
 *
 *   src/Enums/Country.php    one case per ISO 3166-1 country
 *   src/Enums/Currency.php   one case per ISO 4217 code in use
 *   src/Enums/Language.php   one case per ISO 639-3 code in use
 *
 * Usage:  php tools/generate-enums.php [--check]
 *
 * ## Why these are generated and not hand-written
 *
 * The application enum this replaces carried 250 class constants **and three
 * ~240-arm `match` tables** — `getCallingPrefix()`, `getFlagEmoji()`,
 * `getName()` — about 800 lines of data pretending to be code. All three are
 * already in the dataset, and the flag is derivable from the code itself, so
 * here they are lookups and the enum is a list of cases.
 *
 * ## Case names must not depend on the machine
 *
 * Names come from `Text::transliterate()`, an explicit table, and never from
 * `iconv('UTF-8', 'ASCII//TRANSLIT', …)`, whose output differs between glibc
 * and BSD. Measured on macOS, `é` becomes `'e` and `ã` becomes `~a`, so
 * `São Tomé and Príncipe` transliterates to `S~ao Tom'e and Pr'incipe` and the
 * case name derived from it is `SAoTomEAndPrIncipe` — against `SaoTomeAndPrincipe`
 * on Linux. (`Å` and `ç` survive on both, which is what makes this the kind of
 * difference that is noticed late.)
 *
 * The output is committed and `--check`ed, and that gate only means anything if
 * two machines produce the same bytes.
 */
require_once dirname(__DIR__).'/vendor/autoload.php';

use Simtabi\Laranail\Atlas\Core\Support\Text;

$root = dirname(__DIR__);
$check = in_array('--check', $argv, true);

/** @var array<string, array<string, mixed>> $countries */
$countries = require $root.'/resources/data/countries.php';

if ($countries === []) {
    fwrite(STDERR, "The dataset is empty; run tools/build-dataset.php first.\n");

    exit(1);
}

/**
 * A PHP-legal, stable case name.
 *
 * Digits are stripped of nothing and a leading digit is prefixed, because a
 * case name cannot start with one. Nothing here silently drops a character: a
 * name that cannot be expressed is a hard failure below, not a quiet rename.
 */
$caseName = static function (string $name): string {
    $ascii = Text::transliterate($name);
    $words = preg_replace('/[^A-Za-z0-9]+/', ' ', $ascii) ?? '';
    $studly = str_replace(' ', '', ucwords(strtolower(trim($words))));

    return $studly === '' ? '' : (ctype_digit($studly[0]) ? 'C'.$studly : $studly);
};

/**
 * @param  array<string, string>  $cases  case name => backed value
 */
$render = static function (string $class, array $cases, string $summary, string $body = ''): string {
    $count = count($cases);
    $lines = '';

    foreach ($cases as $name => $value) {
        $lines .= sprintf("    case %s = %s;\n", $name, var_export($value, true));
    }

    $trailing = $body === '' ? '' : "\n".$body;

    return <<<PHP
        <?php

        declare(strict_types=1);

        namespace Simtabi\\Laranail\\Atlas\\Enums;

        /**
         * GENERATED by tools/generate-enums.php — do not edit by hand.
         *
         * {$summary}
         *
         * {$count} cases, generated from resources/data/countries.php. Regenerate with
         * `php tools/generate-enums.php`; `--check` gates it in CI.
         */
        enum {$class}: string
        {
        {$lines}{$trailing}}

        PHP;
};

/** @var array<string, array{name: string, cases: array<string, string>, summary: string, body: string}> $targets */
$targets = [];

// ---- Country ---------------------------------------------------------------

$countryCases = [];
$collisions = [];

foreach ($countries as $iso2 => $row) {
    $name = is_string($row['name'] ?? null) ? $row['name'] : '';
    $case = $caseName($name);

    if ($case === '') {
        fwrite(STDERR, "Cannot derive a case name for [{$iso2}] from '{$name}'.\n");

        exit(1);
    }

    // Two countries normalising to one case name would be a fatal enum
    // redeclaration in the generated file. Refuse to write it rather than
    // silently dropping one — the dataset has no collisions today and this is
    // what makes that a checked fact rather than an assumption.
    if (isset($countryCases[$case])) {
        $collisions[] = sprintf("'%s' and '%s' both normalise to %s", $countryCases[$case], $iso2, $case);
    }

    $countryCases[$case] = (string) $iso2;
}

if ($collisions !== []) {
    fwrite(STDERR, "Case-name collisions:\n  ".implode("\n  ", $collisions)."\n");

    exit(1);
}

$targets['Country'] = [
    'file' => $root.'/src/Enums/Country.php',
    'code' => $render(
        'Country',
        $countryCases,
        "Every country in the catalogue, keyed by ISO 3166-1 alpha-2.\n *\n"
        ." * A typed key, not a record. Names, calling codes, currencies and coordinates live in the\n"
        ." * dataset and are reached with `Atlas::country(Country::KE->value)` — the enum this replaces\n"
        ." * carried them as three ~240-arm match tables, which is data wearing code's clothes.",
    ),
];

// ---- Currency and Language -------------------------------------------------

$currencyCases = [];
$languageCases = [];

foreach ($countries as $row) {
    foreach ((array) ($row['currencies'] ?? []) as $code) {
        if (is_string($code) && preg_match('/^[A-Z]{3}$/', $code) === 1) {
            $currencyCases[$code] = $code;
        }
    }

    foreach ((array) ($row['languages'] ?? []) as $code) {
        if (is_string($code) && preg_match('/^[a-z]{2,3}$/', $code) === 1) {
            $languageCases[strtoupper($code)] = $code;
        }
    }
}

ksort($currencyCases);
ksort($languageCases);

$targets['Currency'] = [
    'file' => $root.'/src/Enums/Currency.php',
    'code' => $render(
        'Currency',
        $currencyCases,
        "Every ISO 4217 code in use by a country in the catalogue.\n *\n"
        ." * Derived from the countries rather than from a separate register, so it can never list a\n"
        .' * currency no country uses — and never miss one that a country does.',
    ),
];

$targets['Language'] = [
    'file' => $root.'/src/Enums/Language.php',
    'code' => $render(
        'Language',
        $languageCases,
        "Every ISO 639-3 code spoken in a country in the catalogue.\n *\n"
        ." * Case names are upper-cased because a PHP case name is case-sensitive and `swa` beside\n"
        .' * `SWA` would read as two languages; the backing value keeps the canonical lower-case form.',
    ),
];

// ---- Write or check --------------------------------------------------------

$stale = [];

foreach ($targets as $label => $target) {
    if ($check) {
        $current = is_file($target['file']) ? (string) file_get_contents($target['file']) : '';

        if ($current !== $target['code']) {
            $stale[] = $label;
        }

        continue;
    }

    file_put_contents($target['file'], $target['code']);
    fwrite(STDOUT, sprintf("  %-10s %d cases\n", $label, substr_count($target['code'], "\n    case ")));
}

if ($check) {
    if ($stale !== []) {
        fwrite(STDERR, 'Generated enums are stale: '.implode(', ', $stale)."\n\n"
            ."Either they were edited by hand, or the dataset moved without them. Run\n"
            ."`php tools/generate-enums.php` and read the diff before committing it.\n");

        exit(1);
    }

    fwrite(STDOUT, sprintf("Enums are in sync (%s).\n", implode(', ', array_keys($targets))));
}

exit(0);
